"""Generated LLVM helper emitters for LLVM-native byte descriptors."""


def emit_bytes_get_u16_helper(out, name, little_endian):
    hi = "b1_64" if little_endian else "b0_64"
    lo = "b0_64" if little_endian else "b1_64"
    out.write("\n")
    out.write(f"define i64 @oren_llvm_helper_{name}(i64 %bytes_handle, i64 %idx) nounwind {{\n")
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %bytes_handle, 0\n")
    out.write("  br i1 %is_null, label %invalid, label %load\n")
    out.write("load:\n")
    out.write("  %bytes = inttoptr i64 %bytes_handle to %oren_llvm_bytes*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %bytes, i32 0, i32 0\n")
    out.write("  %len = load i64, i64* %lenp, align 8\n")
    out.write("  %max_idx = sub i64 %len, 2\n")
    out.write("  %idx_nonneg = icmp sge i64 %idx, 0\n")
    out.write("  %idx_in = icmp sle i64 %idx, %max_idx\n")
    out.write("  %ok = and i1 %idx_nonneg, %idx_in\n")
    out.write("  br i1 %ok, label %read, label %invalid\n")
    out.write("read:\n")
    out.write("  %datap = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %bytes, i32 0, i32 1\n")
    out.write("  %data = load i8*, i8** %datap, align 8\n")
    out.write("  %p0 = getelementptr inbounds i8, i8* %data, i64 %idx\n")
    out.write("  %idx1 = add i64 %idx, 1\n")
    out.write("  %p1 = getelementptr inbounds i8, i8* %data, i64 %idx1\n")
    out.write("  %b0 = load i8, i8* %p0, align 1\n")
    out.write("  %b1 = load i8, i8* %p1, align 1\n")
    out.write("  %b0_64 = zext i8 %b0 to i64\n")
    out.write("  %b1_64 = zext i8 %b1 to i64\n")
    out.write(f"  %hi = shl i64 %{hi}, 8\n")
    out.write(f"  %ret = or i64 %hi, %{lo}\n")
    out.write("  ret i64 %ret\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")


def emit_bytes_get_u32_helper(out, name, little_endian):
    order = ["b3_64", "b2_64", "b1_64", "b0_64"] if little_endian else ["b0_64", "b1_64", "b2_64", "b3_64"]
    out.write("\n")
    out.write(f"define i64 @oren_llvm_helper_{name}(i64 %bytes_handle, i64 %idx) nounwind {{\n")
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %bytes_handle, 0\n")
    out.write("  br i1 %is_null, label %invalid, label %load\n")
    out.write("load:\n")
    out.write("  %bytes = inttoptr i64 %bytes_handle to %oren_llvm_bytes*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %bytes, i32 0, i32 0\n")
    out.write("  %len = load i64, i64* %lenp, align 8\n")
    out.write("  %max_idx = sub i64 %len, 4\n")
    out.write("  %idx_nonneg = icmp sge i64 %idx, 0\n")
    out.write("  %idx_in = icmp sle i64 %idx, %max_idx\n")
    out.write("  %ok = and i1 %idx_nonneg, %idx_in\n")
    out.write("  br i1 %ok, label %read, label %invalid\n")
    out.write("read:\n")
    out.write("  %datap = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %bytes, i32 0, i32 1\n")
    out.write("  %data = load i8*, i8** %datap, align 8\n")
    for idx in range(4):
        out.write(f"  %idx{idx} = add i64 %idx, {idx}\n")
        out.write(f"  %p{idx} = getelementptr inbounds i8, i8* %data, i64 %idx{idx}\n")
        out.write(f"  %b{idx} = load i8, i8* %p{idx}, align 1\n")
        out.write(f"  %b{idx}_64 = zext i8 %b{idx} to i64\n")
    out.write(f"  %s0 = shl i64 %{order[0]}, 24\n")
    out.write(f"  %s1 = shl i64 %{order[1]}, 16\n")
    out.write(f"  %s2 = shl i64 %{order[2]}, 8\n")
    out.write("  %v0 = or i64 %s0, %s1\n")
    out.write("  %v1 = or i64 %v0, %s2\n")
    out.write(f"  %ret = or i64 %v1, %{order[3]}\n")
    out.write("  ret i64 %ret\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")


def emit_bytes_set_u8_helper(out):
    out.write("\n")
    out.write("define i64 @oren_llvm_helper_oren_bytes_set_u8(i64 %bytes_handle, i64 %idx, i64 %value) nounwind {\n")
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %bytes_handle, 0\n")
    out.write("  br i1 %is_null, label %invalid, label %load\n")
    out.write("load:\n")
    out.write("  %bytes = inttoptr i64 %bytes_handle to %oren_llvm_bytes*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %bytes, i32 0, i32 0\n")
    out.write("  %len = load i64, i64* %lenp, align 8\n")
    out.write("  %idx_nonneg = icmp sge i64 %idx, 0\n")
    out.write("  %idx_lt_len = icmp slt i64 %idx, %len\n")
    out.write("  %idx_ok = and i1 %idx_nonneg, %idx_lt_len\n")
    out.write("  %value_nonneg = icmp sge i64 %value, 0\n")
    out.write("  %value_in = icmp sle i64 %value, 255\n")
    out.write("  %value_ok = and i1 %value_nonneg, %value_in\n")
    out.write("  %ok = and i1 %idx_ok, %value_ok\n")
    out.write("  br i1 %ok, label %write, label %invalid\n")
    out.write("write:\n")
    out.write("  %datap = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %bytes, i32 0, i32 1\n")
    out.write("  %data = load i8*, i8** %datap, align 8\n")
    out.write("  %ptr = getelementptr inbounds i8, i8* %data, i64 %idx\n")
    out.write("  %byte = trunc i64 %value to i8\n")
    out.write("  store i8 %byte, i8* %ptr, align 1\n")
    out.write("  ret i64 %value\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")


def emit_u8_buf_from_bytes_slice_helper(out):
    out.write("\n")
    out.write(
        "define i64 @oren_llvm_helper_oren_u8_buf_from_bytes_slice("
        "i64 %argc, i64 %arg0, i64 %arg1, i64 %arg2, i64 %arg3) nounwind {\n"
    )
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %arg0, 0\n")
    out.write("  br i1 %is_null, label %invalid, label %load\n")
    out.write("load:\n")
    out.write("  %src = inttoptr i64 %arg0 to %oren_llvm_bytes*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %src, i32 0, i32 0\n")
    out.write("  %src_len = load i64, i64* %lenp, align 8\n")
    out.write("  %start_nonneg = icmp sge i64 %arg1, 0\n")
    out.write("  %len_nonneg = icmp sge i64 %arg2, 0\n")
    out.write("  %space = sub i64 %src_len, %arg2\n")
    out.write("  %start_in = icmp sle i64 %arg1, %space\n")
    out.write("  %ok_a = and i1 %start_nonneg, %len_nonneg\n")
    out.write("  %ok = and i1 %ok_a, %start_in\n")
    out.write("  br i1 %ok, label %copy, label %invalid\n")
    out.write("copy:\n")
    out.write("  %src_datap = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %src, i32 0, i32 1\n")
    out.write("  %src_data = load i8*, i8** %src_datap, align 8\n")
    out.write("  %out_handle = call i64 @oren_llvm_runtime_alloc_bytes_desc(i64 %arg2)\n")
    out.write("  %out_desc = inttoptr i64 %out_handle to %oren_llvm_bytes*\n")
    out.write("  %out_datap = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %out_desc, i32 0, i32 1\n")
    out.write("  %out_data = load i8*, i8** %out_datap, align 8\n")
    out.write("  %src_start = getelementptr inbounds i8, i8* %src_data, i64 %arg1\n")
    out.write("  call i8* @memcpy(i8* %out_data, i8* %src_start, i64 %arg2)\n")
    out.write("  ret i64 %out_handle\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")


def emit_string_from_bytes_slice_helper(out):
    out.write("\n")
    out.write(
        "define i64 @oren_llvm_helper_oren_string_from_bytes_slice("
        "i64 %argc, i64 %arg0, i64 %arg1, i64 %arg2, i64 %arg3) nounwind {\n"
    )
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %arg0, 0\n")
    out.write("  br i1 %is_null, label %invalid, label %load\n")
    out.write("load:\n")
    out.write("  %src = inttoptr i64 %arg0 to %oren_llvm_bytes*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %src, i32 0, i32 0\n")
    out.write("  %src_len = load i64, i64* %lenp, align 8\n")
    out.write("  %start_nonneg = icmp sge i64 %arg1, 0\n")
    out.write("  %len_nonneg = icmp sge i64 %arg2, 0\n")
    out.write("  %space = sub i64 %src_len, %arg2\n")
    out.write("  %start_in = icmp sle i64 %arg1, %space\n")
    out.write("  %ok_a = and i1 %start_nonneg, %len_nonneg\n")
    out.write("  %ok = and i1 %ok_a, %start_in\n")
    out.write("  br i1 %ok, label %copy, label %invalid\n")
    out.write("copy:\n")
    out.write("  %src_datap = getelementptr inbounds %oren_llvm_bytes, %oren_llvm_bytes* %src, i32 0, i32 1\n")
    out.write("  %src_data = load i8*, i8** %src_datap, align 8\n")
    out.write("  %out_handle = call i64 @oren_llvm_runtime_alloc_string(i64 %arg2)\n")
    out.write("  %out_desc = inttoptr i64 %out_handle to %oren_llvm_string*\n")
    out.write("  %out_datap = getelementptr inbounds %oren_llvm_string, %oren_llvm_string* %out_desc, i32 0, i32 1\n")
    out.write("  %out_data = load i8*, i8** %out_datap, align 8\n")
    out.write("  %src_start = getelementptr inbounds i8, i8* %src_data, i64 %arg1\n")
    out.write("  call i8* @memcpy(i8* %out_data, i8* %src_start, i64 %arg2)\n")
    out.write("  ret i64 %out_handle\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")
