"""Generated LLVM helper emitters for LLVM-native map descriptors."""


def emit_map_runtime_alloc(out):
    out.write("\n")
    out.write("define i64 @oren_llvm_runtime_alloc_map(i64 %cap) nounwind {\n")
    out.write("entry:\n")
    out.write("  %neg = icmp slt i64 %cap, 0\n")
    out.write("  br i1 %neg, label %invalid, label %alloc\n")
    out.write("alloc:\n")
    out.write("  %cap_bytes = mul i64 %cap, 8\n")
    out.write("  %raw_keys = call i8* @oren_llvm_runtime_alloc_bytes(i64 %cap_bytes, i64 3)\n")
    out.write("  %raw_values = call i8* @oren_llvm_runtime_alloc_bytes(i64 %cap_bytes, i64 3)\n")
    out.write("  %raw_key_kinds = call i8* @oren_llvm_runtime_alloc_bytes(i64 %cap_bytes, i64 3)\n")
    out.write("  %raw_desc = call i8* @oren_llvm_runtime_alloc_bytes(i64 48, i64 4)\n")
    out.write("  %keys = bitcast i8* %raw_keys to i64*\n")
    out.write("  %values = bitcast i8* %raw_values to i64*\n")
    out.write("  %key_kinds = bitcast i8* %raw_key_kinds to i64*\n")
    out.write("  %desc = bitcast i8* %raw_desc to %oren_llvm_map*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %desc, i32 0, i32 0\n")
    out.write("  store i64 0, i64* %lenp, align 8\n")
    out.write("  %keysp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %desc, i32 0, i32 1\n")
    out.write("  store i64* %keys, i64** %keysp, align 8\n")
    out.write("  %valuesp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %desc, i32 0, i32 2\n")
    out.write("  store i64* %values, i64** %valuesp, align 8\n")
    out.write("  %kindsp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %desc, i32 0, i32 3\n")
    out.write("  store i64* %key_kinds, i64** %kindsp, align 8\n")
    out.write("  %ownerp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %desc, i32 0, i32 4\n")
    out.write("  store i64 1, i64* %ownerp, align 8\n")
    out.write("  %capp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %desc, i32 0, i32 5\n")
    out.write("  store i64 %cap, i64* %capp, align 8\n")
    out.write("  %ret = ptrtoint %oren_llvm_map* %desc to i64\n")
    out.write("  call void @oren_llvm_runtime_register_map(i64 %ret, i64* %keys, i64* %values, i64* %key_kinds, i64 0, i64 %cap)\n")
    out.write("  ret i64 %ret\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")


def emit_map_len_helper(out):
    out.write("\n")
    out.write("define i64 @oren_llvm_helper_oren_map_len(i64 %map_handle) nounwind {\n")
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %map_handle, 0\n")
    out.write("  br i1 %is_null, label %invalid, label %load\n")
    out.write("load:\n")
    out.write("  %map = inttoptr i64 %map_handle to %oren_llvm_map*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 0\n")
    out.write("  %len = load i64, i64* %lenp, align 8\n")
    out.write("  ret i64 %len\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")


def emit_map_find_helper(out):
    out.write("\n")
    out.write("define i64 @oren_llvm_helper_oren_map_find(i64 %map_handle, i64 %key) nounwind {\n")
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %map_handle, 0\n")
    out.write("  br i1 %is_null, label %missing, label %load\n")
    out.write("load:\n")
    out.write("  %map = inttoptr i64 %map_handle to %oren_llvm_map*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 0\n")
    out.write("  %len = load i64, i64* %lenp, align 8\n")
    out.write("  %keysp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 1\n")
    out.write("  %keys = load i64*, i64** %keysp, align 8\n")
    out.write("  %kindsp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 3\n")
    out.write("  %kinds = load i64*, i64** %kindsp, align 8\n")
    out.write("  br label %loop\n")
    out.write("loop:\n")
    out.write("  %i = phi i64 [0, %load], [%next, %step]\n")
    out.write("  %done = icmp sge i64 %i, %len\n")
    out.write("  br i1 %done, label %missing, label %check\n")
    out.write("check:\n")
    out.write("  %kindp = getelementptr inbounds i64, i64* %kinds, i64 %i\n")
    out.write("  %kind = load i64, i64* %kindp, align 8\n")
    out.write("  %is_exact = icmp eq i64 %kind, 0\n")
    out.write("  br i1 %is_exact, label %check_key, label %step\n")
    out.write("check_key:\n")
    out.write("  %keyp = getelementptr inbounds i64, i64* %keys, i64 %i\n")
    out.write("  %cur = load i64, i64* %keyp, align 8\n")
    out.write("  %eq = icmp eq i64 %cur, %key\n")
    out.write("  br i1 %eq, label %found, label %step\n")
    out.write("step:\n")
    out.write("  %next = add i64 %i, 1\n")
    out.write("  br label %loop\n")
    out.write("found:\n")
    out.write("  ret i64 %i\n")
    out.write("missing:\n")
    out.write("  ret i64 -1\n")
    out.write("}\n")


def emit_map_find_string_helper(out):
    out.write("\n")
    out.write("define i64 @oren_llvm_helper_oren_map_find_string(i64 %map_handle, i64 %key) nounwind {\n")
    out.write("entry:\n")
    out.write("  %bad_map = icmp eq i64 %map_handle, 0\n")
    out.write("  %bad_key = icmp eq i64 %key, 0\n")
    out.write("  %bad = or i1 %bad_map, %bad_key\n")
    out.write("  br i1 %bad, label %missing, label %load\n")
    out.write("load:\n")
    out.write("  %map = inttoptr i64 %map_handle to %oren_llvm_map*\n")
    out.write("  %want = inttoptr i64 %key to %oren_llvm_string*\n")
    out.write("  %want_lenp = getelementptr inbounds %oren_llvm_string, %oren_llvm_string* %want, i32 0, i32 0\n")
    out.write("  %want_len = load i64, i64* %want_lenp, align 8\n")
    out.write("  %want_datap = getelementptr inbounds %oren_llvm_string, %oren_llvm_string* %want, i32 0, i32 1\n")
    out.write("  %want_data = load i8*, i8** %want_datap, align 8\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 0\n")
    out.write("  %len = load i64, i64* %lenp, align 8\n")
    out.write("  %keysp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 1\n")
    out.write("  %keys = load i64*, i64** %keysp, align 8\n")
    out.write("  %kindsp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 3\n")
    out.write("  %kinds = load i64*, i64** %kindsp, align 8\n")
    out.write("  br label %loop\n")
    out.write("loop:\n")
    out.write("  %i = phi i64 [0, %load], [%next, %step]\n")
    out.write("  %done = icmp sge i64 %i, %len\n")
    out.write("  br i1 %done, label %missing, label %check_kind\n")
    out.write("check_kind:\n")
    out.write("  %kindp = getelementptr inbounds i64, i64* %kinds, i64 %i\n")
    out.write("  %kind = load i64, i64* %kindp, align 8\n")
    out.write("  %is_string = icmp eq i64 %kind, 1\n")
    out.write("  br i1 %is_string, label %check_len, label %step\n")
    out.write("check_len:\n")
    out.write("  %keyp = getelementptr inbounds i64, i64* %keys, i64 %i\n")
    out.write("  %cur = load i64, i64* %keyp, align 8\n")
    out.write("  %cur_desc = inttoptr i64 %cur to %oren_llvm_string*\n")
    out.write("  %cur_lenp = getelementptr inbounds %oren_llvm_string, %oren_llvm_string* %cur_desc, i32 0, i32 0\n")
    out.write("  %cur_len = load i64, i64* %cur_lenp, align 8\n")
    out.write("  %same_len = icmp eq i64 %cur_len, %want_len\n")
    out.write("  br i1 %same_len, label %check_data, label %step\n")
    out.write("check_data:\n")
    out.write("  %cur_datap = getelementptr inbounds %oren_llvm_string, %oren_llvm_string* %cur_desc, i32 0, i32 1\n")
    out.write("  %cur_data = load i8*, i8** %cur_datap, align 8\n")
    out.write("  %cmp = call i32 @memcmp(i8* %cur_data, i8* %want_data, i64 %want_len)\n")
    out.write("  %eq = icmp eq i32 %cmp, 0\n")
    out.write("  br i1 %eq, label %found, label %step\n")
    out.write("step:\n")
    out.write("  %next = add i64 %i, 1\n")
    out.write("  br label %loop\n")
    out.write("found:\n")
    out.write("  ret i64 %i\n")
    out.write("missing:\n")
    out.write("  ret i64 -1\n")
    out.write("}\n")


def emit_map_get_helper(out):
    out.write("\n")
    out.write("define i64 @oren_llvm_helper_oren_map_get(i64 %map_handle, i64 %key) nounwind {\n")
    out.write("entry:\n")
    out.write("  %idx = call i64 @oren_llvm_helper_oren_map_find(i64 %map_handle, i64 %key)\n")
    out.write("  %missing = icmp slt i64 %idx, 0\n")
    out.write("  br i1 %missing, label %invalid, label %read\n")
    out.write("read:\n")
    out.write("  %map = inttoptr i64 %map_handle to %oren_llvm_map*\n")
    out.write("  %valuesp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 2\n")
    out.write("  %values = load i64*, i64** %valuesp, align 8\n")
    out.write("  %valuep = getelementptr inbounds i64, i64* %values, i64 %idx\n")
    out.write("  %value = load i64, i64* %valuep, align 8\n")
    out.write("  ret i64 %value\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")


def emit_map_get_string_helper(out):
    out.write("\n")
    out.write("define i64 @oren_llvm_helper_oren_map_get_string(i64 %map_handle, i64 %key) nounwind {\n")
    out.write("entry:\n")
    out.write("  %idx = call i64 @oren_llvm_helper_oren_map_find_string(i64 %map_handle, i64 %key)\n")
    out.write("  %missing = icmp slt i64 %idx, 0\n")
    out.write("  br i1 %missing, label %invalid, label %read\n")
    out.write("read:\n")
    out.write("  %map = inttoptr i64 %map_handle to %oren_llvm_map*\n")
    out.write("  %valuesp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 2\n")
    out.write("  %values = load i64*, i64** %valuesp, align 8\n")
    out.write("  %valuep = getelementptr inbounds i64, i64* %values, i64 %idx\n")
    out.write("  %value = load i64, i64* %valuep, align 8\n")
    out.write("  ret i64 %value\n")
    out.write("invalid:\n")
    out.write("  ret i64 0\n")
    out.write("}\n")


def emit_map_store_new_helper(out):
    out.write("\n")
    out.write("define void @oren_llvm_helper_oren_map_store_new(i64 %map_handle, i64 %key, i64 %key_kind, i64 %value) nounwind {\n")
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %map_handle, 0\n")
    out.write("  br i1 %is_null, label %done, label %insert\n")
    out.write("insert:\n")
    out.write("  %map = inttoptr i64 %map_handle to %oren_llvm_map*\n")
    out.write("  %lenp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 0\n")
    out.write("  %len = load i64, i64* %lenp, align 8\n")
    out.write("  %capp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 5\n")
    out.write("  %cap = load i64, i64* %capp, align 8\n")
    out.write("  %has_room = icmp slt i64 %len, %cap\n")
    out.write("  br i1 %has_room, label %write, label %grow\n")
    out.write("grow:\n")
    out.write("  %double_cap = mul i64 %cap, 2\n")
    out.write("  %cap_too_small = icmp slt i64 %double_cap, 4\n")
    out.write("  %next_cap = select i1 %cap_too_small, i64 4, i64 %double_cap\n")
    out.write("  %copy_bytes = mul i64 %len, 8\n")
    out.write("  %new_bytes = mul i64 %next_cap, 8\n")
    out.write("  %keysp0 = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 1\n")
    out.write("  %old_keys = load i64*, i64** %keysp0, align 8\n")
    out.write("  %valuesp0 = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 2\n")
    out.write("  %old_values = load i64*, i64** %valuesp0, align 8\n")
    out.write("  %kindsp0 = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 3\n")
    out.write("  %old_kinds = load i64*, i64** %kindsp0, align 8\n")
    out.write("  %new_keys_raw = call i8* @oren_llvm_runtime_alloc_bytes(i64 %new_bytes, i64 3)\n")
    out.write("  %new_values_raw = call i8* @oren_llvm_runtime_alloc_bytes(i64 %new_bytes, i64 3)\n")
    out.write("  %new_kinds_raw = call i8* @oren_llvm_runtime_alloc_bytes(i64 %new_bytes, i64 3)\n")
    out.write("  %old_keys_raw = bitcast i64* %old_keys to i8*\n")
    out.write("  %old_values_raw = bitcast i64* %old_values to i8*\n")
    out.write("  %old_kinds_raw = bitcast i64* %old_kinds to i8*\n")
    out.write("  call i8* @memcpy(i8* %new_keys_raw, i8* %old_keys_raw, i64 %copy_bytes)\n")
    out.write("  call i8* @memcpy(i8* %new_values_raw, i8* %old_values_raw, i64 %copy_bytes)\n")
    out.write("  call i8* @memcpy(i8* %new_kinds_raw, i8* %old_kinds_raw, i64 %copy_bytes)\n")
    out.write("  %new_keys = bitcast i8* %new_keys_raw to i64*\n")
    out.write("  %new_values = bitcast i8* %new_values_raw to i64*\n")
    out.write("  %new_kinds = bitcast i8* %new_kinds_raw to i64*\n")
    out.write("  store i64* %new_keys, i64** %keysp0, align 8\n")
    out.write("  store i64* %new_values, i64** %valuesp0, align 8\n")
    out.write("  store i64* %new_kinds, i64** %kindsp0, align 8\n")
    out.write("  store i64 %next_cap, i64* %capp, align 8\n")
    out.write("  br label %write\n")
    out.write("write:\n")
    out.write("  %keysp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 1\n")
    out.write("  %keys = load i64*, i64** %keysp, align 8\n")
    out.write("  %valuesp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 2\n")
    out.write("  %values = load i64*, i64** %valuesp, align 8\n")
    out.write("  %kindsp = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 3\n")
    out.write("  %kinds = load i64*, i64** %kindsp, align 8\n")
    out.write("  %key_slot = getelementptr inbounds i64, i64* %keys, i64 %len\n")
    out.write("  %value_slot = getelementptr inbounds i64, i64* %values, i64 %len\n")
    out.write("  %kind_slot = getelementptr inbounds i64, i64* %kinds, i64 %len\n")
    out.write("  store i64 %key, i64* %key_slot, align 8\n")
    out.write("  store i64 %value, i64* %value_slot, align 8\n")
    out.write("  store i64 %key_kind, i64* %kind_slot, align 8\n")
    out.write("  %next_len = add i64 %len, 1\n")
    out.write("  store i64 %next_len, i64* %lenp, align 8\n")
    out.write("  ret void\n")
    out.write("done:\n")
    out.write("  ret void\n")
    out.write("}\n")


def emit_map_set_helper(out):
    out.write("\n")
    out.write("define void @oren_llvm_helper_oren_map_set(i64 %map_handle, i64 %key, i64 %value) nounwind {\n")
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %map_handle, 0\n")
    out.write("  br i1 %is_null, label %done, label %load\n")
    out.write("load:\n")
    out.write("  %map = inttoptr i64 %map_handle to %oren_llvm_map*\n")
    out.write("  %idx = call i64 @oren_llvm_helper_oren_map_find(i64 %map_handle, i64 %key)\n")
    out.write("  %found = icmp sge i64 %idx, 0\n")
    out.write("  br i1 %found, label %replace, label %insert\n")
    out.write("replace:\n")
    out.write("  %valuesp0 = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 2\n")
    out.write("  %values0 = load i64*, i64** %valuesp0, align 8\n")
    out.write("  %slot0 = getelementptr inbounds i64, i64* %values0, i64 %idx\n")
    out.write("  store i64 %value, i64* %slot0, align 8\n")
    out.write("  ret void\n")
    out.write("insert:\n")
    out.write("  call void @oren_llvm_helper_oren_map_store_new(i64 %map_handle, i64 %key, i64 0, i64 %value)\n")
    out.write("  ret void\n")
    out.write("done:\n")
    out.write("  ret void\n")
    out.write("}\n")


def emit_map_set_string_helper(out):
    out.write("\n")
    out.write("define void @oren_llvm_helper_oren_map_set_string(i64 %map_handle, i64 %key, i64 %value) nounwind {\n")
    out.write("entry:\n")
    out.write("  %is_null = icmp eq i64 %map_handle, 0\n")
    out.write("  br i1 %is_null, label %done, label %load\n")
    out.write("load:\n")
    out.write("  %map = inttoptr i64 %map_handle to %oren_llvm_map*\n")
    out.write("  %idx = call i64 @oren_llvm_helper_oren_map_find_string(i64 %map_handle, i64 %key)\n")
    out.write("  %found = icmp sge i64 %idx, 0\n")
    out.write("  br i1 %found, label %replace, label %insert\n")
    out.write("replace:\n")
    out.write("  %valuesp0 = getelementptr inbounds %oren_llvm_map, %oren_llvm_map* %map, i32 0, i32 2\n")
    out.write("  %values0 = load i64*, i64** %valuesp0, align 8\n")
    out.write("  %slot0 = getelementptr inbounds i64, i64* %values0, i64 %idx\n")
    out.write("  store i64 %value, i64* %slot0, align 8\n")
    out.write("  ret void\n")
    out.write("insert:\n")
    out.write("  call void @oren_llvm_helper_oren_map_store_new(i64 %map_handle, i64 %key, i64 1, i64 %value)\n")
    out.write("  ret void\n")
    out.write("done:\n")
    out.write("  ret void\n")
    out.write("}\n")
