#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

usage() {
  cat >&2 <<'EOF'
usage: scripts/run_avm_package_policy.sh <source.oren> [-- <avm-args...>]

Builds <source.oren> as bytecode with --manifest, reads policy.source_package,
then runs ./avm with the declared package policy applied:
  - runtime_profile="capsule" -> AVM_CAPSULE=1 plus AVM_ALLOW_DOMAINS
  - budget_gas -> AVM_GAS
  - budget_heap_bytes -> AVM_MEM_BYTES
  - budget_wall_ms -> AVM_TIMEOUT_MS

Existing stricter env budgets are preserved. Broader env budgets are narrowed to
the package declaration. Use -- <avm-args...> to pass normal AVM flags.

Generated bytecode is removed on exit by default. Set
OREN_AVM_PACKAGE_POLICY_KEEP_OBC=1, or provide OREN_AVM_PACKAGE_POLICY_OBC, to
keep the generated bytecode and manifest for inspection.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ "$#" -lt 1 ]]; then
  usage
  exit 2
fi

src="$1"
shift
if [[ "$#" -gt 0 && "${1:-}" == "--" ]]; then
  shift
fi

if [[ ! -f "$src" ]]; then
  echo "ERROR: missing source: $src" >&2
  exit 2
fi

mkdir -p build/logs build/tmp
ts="$(date +%Y%m%d_%H%M%S)"
base="$(basename "$src" .oren | tr -c 'A-Za-z0-9_-' '_')"
obc="${OREN_AVM_PACKAGE_POLICY_OBC:-build/tmp/avm_package_policy_${base}_${ts}.obc}"
build_log="${OREN_AVM_PACKAGE_POLICY_BUILD_LOG:-build/logs/avm_package_policy_${base}_${ts}.build.log}"
cleanup_obc=1
if [[ -n "${OREN_AVM_PACKAGE_POLICY_KEEP_OBC:-}" || -n "${OREN_AVM_PACKAGE_POLICY_OBC:-}" ]]; then
  cleanup_obc=0
fi

cleanup() {
  if [[ "$cleanup_obc" == "1" ]]; then
    rm -f "$obc" "$obc.manifest.json"
  fi
}
trap cleanup EXIT

./oren build "$src" --backend bytecode --manifest -o "$obc" >"$build_log" 2>&1

python3 - "$obc" "$obc.manifest.json" -- "$@" <<'PY'
import json
import os
import subprocess
import sys

DOMAIN_IDS = {
    "CORE": 0,
    "FS": 1,
    "TIME": 2,
    "RNG": 3,
    "NET": 4,
    "PROC": 5,
    "EXIT": 6,
    "ENV": 7,
    "AVM": 8,
}

def fail(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(2)

def positive_int(value, name):
    try:
        out = int(value)
    except (TypeError, ValueError):
        fail(f"{name} must be a positive integer, got {value!r}")
    if out <= 0:
        fail(f"{name} must be a positive integer, got {value!r}")
    return out

def narrow_env_budget(env, env_key, declared):
    if declared is None:
        return
    declared_i = positive_int(declared, env_key)
    current = env.get(env_key)
    if current:
        try:
            current_i = int(current)
        except ValueError:
            fail(f"{env_key} must be numeric when set, got {current!r}")
        if current_i > 0:
            declared_i = min(current_i, declared_i)
    env[env_key] = str(declared_i)

def split_avm_args(args):
    if "--" not in args:
        return args, []
    idx = args.index("--")
    return args[:idx], args[idx + 1:]

def load_policy_json(obc_path, env):
    p = subprocess.run(
        ["./avm", "--print-policy-json", obc_path],
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if p.returncode != 0:
        print(p.stdout, end="", file=sys.stderr)
        print(p.stderr, end="", file=sys.stderr)
        fail(f"failed to scan AVM policy for {obc_path}")
    for line in p.stdout.splitlines():
        line = line.strip()
        if line.startswith("{") and '"schema":"avm.policy.v1"' in line:
            return json.loads(line)
    fail(f"missing avm.policy.v1 JSON for {obc_path}")

obc = sys.argv[1]
manifest_path = sys.argv[2]
rest = sys.argv[3:]
if rest and rest[0] == "--":
    rest = rest[1:]

with open(manifest_path, "r", encoding="utf-8") as f:
    manifest = json.load(f)

policy = manifest.get("policy") or {}
pkg = policy.get("source_package") or {}
if not pkg.get("declared"):
    fail(f"{manifest_path}: missing declared policy.source_package")

env = os.environ.copy()
profile = pkg.get("runtime_profile")
allow_mask = 0
if profile == "capsule":
    env["AVM_CAPSULE"] = "1"
    domain_names = [str(x).upper() for x in (pkg.get("cap_allow_domains") or [])]
    domain_ids = {DOMAIN_IDS["CORE"], DOMAIN_IDS["EXIT"]}
    for name in domain_names:
        if name not in DOMAIN_IDS:
            fail(f"unknown package cap_allow_domains entry {name!r}")
        domain_ids.add(DOMAIN_IDS[name])
    allow_mask = 0
    for domain_id in domain_ids:
        allow_mask |= 1 << domain_id
    env["AVM_ALLOW_DOMAINS"] = ",".join(str(x) for x in sorted(domain_ids))

budgets = pkg.get("budgets") or {}
if budgets.get("declared"):
    narrow_env_budget(env, "AVM_GAS", budgets.get("gas"))
    narrow_env_budget(env, "AVM_MEM_BYTES", budgets.get("heap_bytes"))
    narrow_env_budget(env, "AVM_TIMEOUT_MS", budgets.get("wall_ms"))

avm_opts, prog_args = split_avm_args(rest)
if profile == "capsule":
    policy_json = load_policy_json(obc, env)
    used_mask_s = policy_json.get("used_domains_mask", "0")
    try:
        used_mask = int(str(used_mask_s), 16) if str(used_mask_s).startswith("0x") else int(str(used_mask_s))
    except ValueError:
        fail(f"invalid used_domains_mask from AVM policy scanner: {used_mask_s!r}")
    missing_mask = used_mask & ~allow_mask
    if missing_mask != 0:
        missing = []
        for name, domain_id in sorted(DOMAIN_IDS.items(), key=lambda kv: kv[1]):
            if missing_mask & (1 << domain_id):
                missing.append(name)
        fail(
            "package policy denies AVM domains used by bytecode: "
            + ",".join(missing)
            + f" (used_mask=0x{used_mask:016x} allow_mask=0x{allow_mask:016x})"
        )

cmd = ["./avm", *avm_opts, obc]
if prog_args:
    cmd.extend(["--", *prog_args])

result = subprocess.run(cmd, env=env)
raise SystemExit(result.returncode)
PY
