#!/usr/bin/env python3
"""Verify the AVM stdlib OBC bundle from a manifest.

The manifest is intentionally checked against lib/std/stdlib_avm.oren so adding
or removing app-facing modules cannot silently bypass the OBC link/run gate.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path


IMPORT_RE = re.compile(r'^\s*import\s+([A-Za-z_][A-Za-z0-9_]*)\s+"([^"]+)"\s*$')


def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # pragma: no cover - printed path is the useful part.
        raise SystemExit(f"FAIL: could not read manifest {path}: {exc}") from exc


def parse_imports(path: Path) -> dict[str, str]:
    imports: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = IMPORT_RE.match(line)
        if m:
            imports[m.group(2)] = m.group(1)
    return imports


def check_manifest(manifest: dict, root: Path) -> list[dict]:
    if manifest.get("schema") != "oren.avm.stdlib_surface.v0":
        raise SystemExit("FAIL: unexpected stdlib surface manifest schema")

    stdlib_root = root / manifest.get("stdlib_root", "")
    bundle_imports = parse_imports(stdlib_root)
    modules = manifest.get("modules")
    if not isinstance(modules, list) or not modules:
        raise SystemExit("FAIL: manifest has no modules")

    seen: dict[str, str] = {}
    for entry in modules:
        module = entry.get("module")
        alias = entry.get("alias")
        probes = entry.get("probes")
        if not isinstance(module, str) or not module:
            raise SystemExit("FAIL: manifest module entry missing module")
        if not isinstance(alias, str) or not alias:
            raise SystemExit(f"FAIL: manifest module {module} missing alias")
        if module in seen:
            raise SystemExit(f"FAIL: duplicate manifest module {module}")
        seen[module] = alias
        if bundle_imports.get(module) != alias:
            raise SystemExit(
                "FAIL: manifest alias mismatch for "
                f"{module}: manifest={alias!r} stdlib_avm={bundle_imports.get(module)!r}"
            )
        if not isinstance(probes, list):
            raise SystemExit(f"FAIL: manifest module {module} probes must be a list")
        for probe in probes:
            if not isinstance(probe, str):
                raise SystemExit(f"FAIL: manifest module {module} has non-string probe")

    missing = sorted(set(bundle_imports) - set(seen))
    extra = sorted(set(seen) - set(bundle_imports))
    if missing:
        raise SystemExit("FAIL: stdlib_avm imports missing from manifest: " + ", ".join(missing))
    if extra:
        raise SystemExit("FAIL: manifest modules not imported by stdlib_avm: " + ", ".join(extra))

    exclusions = manifest.get("host_only_exclusions", [])
    if not isinstance(exclusions, list):
        raise SystemExit("FAIL: host_only_exclusions must be a list")
    for exclusion in exclusions:
        module = exclusion.get("module")
        if not isinstance(module, str) or not module:
            raise SystemExit("FAIL: host_only_exclusions entry missing module")
        if module in bundle_imports:
            raise SystemExit(f"FAIL: host-only module imported by stdlib_avm: {module}")

    return modules


def write_source(manifest: dict, modules: list[dict], path: Path) -> None:
    marker = manifest.get("success_marker", "avm stdlib obc surface OK")
    lines: list[str] = [
        "// Generated by scripts/verify_avm_stdlib_obc_surface.py.",
        "// Do not edit; update tests/fixtures/avm_stdlib_obc_surface_manifest.json.",
        "",
    ]
    for entry in modules:
        lines.append(f'import {entry["alias"]} "{entry["module"]}"')
    lines.extend(
        [
            "",
            "fn fail(code) {",
            '    print("avm stdlib obc surface FAIL " + oren_int_to_string(code))',
            "    exit(code)",
            "}",
            "",
            "fn assert_true(v, code) {",
            "    if v { return 0 }",
            "    fail(code)",
            "}",
            "",
            "fn assert_close(a, b, eps, code) {",
            "    var d = a - b",
            "    if d < 0.0 { d = 0.0 - d }",
            "    assert_true(d <= eps, code)",
            "}",
            "",
            "fn main() {",
        ]
    )
    for entry in modules:
        lines.append(f"    // {entry['module']}")
        for probe in entry.get("probes", []):
            if probe:
                lines.append(f"    {probe}")
        lines.append("")
    lines.extend([f'    print("{marker}")', "}", "", "main()", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def run_cmd(argv: list[str], log_path: Path, cwd: Path) -> int:
    with log_path.open("w", encoding="utf-8") as log:
        proc = subprocess.run(argv, cwd=str(cwd), stdout=log, stderr=subprocess.STDOUT, check=False)
    return proc.returncode


def tail(path: Path, lines: int = 160) -> str:
    if not path.exists():
        return ""
    data = path.read_text(encoding="utf-8", errors="replace").splitlines()
    return "\n".join(data[-lines:])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--compiler", default="./oren")
    ap.add_argument("--avm", default="./avm")
    ap.add_argument("--manifest", default="tests/fixtures/avm_stdlib_obc_surface_manifest.json")
    ap.add_argument("--stdlib-obc", default="build/plugins/stdlib_bundle.obc")
    args = ap.parse_args()

    root = Path(__file__).resolve().parents[1]
    manifest_path = root / args.manifest
    manifest = load_json(manifest_path)
    modules = check_manifest(manifest, root)

    (root / "build/tmp").mkdir(parents=True, exist_ok=True)
    (root / "build/logs").mkdir(parents=True, exist_ok=True)
    tag = time.strftime("%Y%m%d_%H%M%S")
    src = root / "build/tmp" / f"avm_stdlib_obc_surface_manifest_{tag}.oren"
    obc = root / "build/tmp" / f"avm_stdlib_obc_surface_manifest_{tag}.obc"
    build_log = root / "build/logs" / f"build_avm_stdlib_obc_surface_manifest_{tag}.log"
    run_log = root / "build/logs" / f"run_avm_stdlib_obc_surface_manifest_{tag}.log"

    write_source(manifest, modules, src)

    compiler = args.compiler
    avm = args.avm
    if not os.access(root / compiler, os.X_OK):
        raise SystemExit(f"FAIL: missing compiler: {compiler}")
    if not os.access(root / avm, os.X_OK):
        raise SystemExit(f"FAIL: missing AVM binary: {avm}")

    build_rc = run_cmd(
        [
            compiler,
            "build",
            str(src),
            "--backend",
            "bytecode",
            "--stdlib-mode",
            "obc",
            "--stdlib-obc",
            args.stdlib_obc,
            "-o",
            str(obc),
        ],
        build_log,
        root,
    )
    if build_rc != 0 or not obc.exists():
        sys.stderr.write(f"FAIL: stdlib OBC surface build failed rc={build_rc}\n")
        sys.stderr.write(tail(build_log) + "\n")
        return build_rc or 3

    run_rc = run_cmd(
        [
            avm,
            "--net-backend",
            "vnet",
            "--net-fixtures-hex",
            manifest["net_fixtures_hex"],
            str(obc),
        ],
        run_log,
        root,
    )
    if run_rc != 0:
        sys.stderr.write(f"FAIL: stdlib OBC surface run failed rc={run_rc}\n")
        sys.stderr.write(tail(run_log) + "\n")
        return run_rc

    output = run_log.read_text(encoding="utf-8", errors="replace")
    marker = manifest.get("success_marker", "avm stdlib obc surface OK")
    if marker not in output:
        sys.stderr.write("FAIL: missing stdlib OBC surface marker\n")
        sys.stderr.write(tail(run_log) + "\n")
        return 4

    print(f"OK: AVM stdlib OBC manifest surface passed ({len(modules)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
