#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

require_file() {
  local path="$1"
  [[ -f "$path" ]] || fail "missing file: $path"
}

require_literal() {
  local path="$1"
  local needle="$2"
  grep -Fq -- "$needle" "$path" || fail "missing literal in $path: $needle"
}

contract="docs/EFFECT_LEDGER_CONTRACT.md"
cap_contract="docs/CAPABILITY_RUNTIME_CONTRACT.md"
docs_index="docs/README.md"
status_doc="docs/STATUS.md"
tasks_doc="docs/BLEEDING_EDGE_TASKS.md"
thesis_doc="docs/OREN_THESIS.md"
horizon_doc="project-doc/oren_feature_horizon_20260412.md"
bets_doc="project-doc/oren_language_system_bets_20260412.md"
avm_main="lib/avm/main.c"
avm_json_guard="scripts/verify_avm_effect_ledger_json.sh"
semantic_diff_runner="scripts/run_backend_semantic_diff.sh"
semantic_diff_guard="scripts/verify_backend_semantic_diff.sh"
gas_calibration_set_guard="scripts/verify_backend_gas_surface_calibration_set.sh"
native_instruction_surface_guard="scripts/verify_backend_native_instruction_surface_decision.sh"
native_gas_modes_guard="scripts/verify_native_gas_accounting_modes.sh"
gas_surface_registry="docs/GAS_SURFACE_REGISTRY.md"
gas_surface_registry_guard="scripts/verify_gas_surface_registry.sh"
native_policy_runner="scripts/run_native_package_policy.sh"
native_policy_runner_guard="scripts/verify_native_package_policy_runner.sh"
native_consts="lib/runtime_native/010_channels_globals_consts.oren"
native_prelude="lib/runtime_native/000_prelude_sys.oren"

for f in \
  "$contract" \
  "$cap_contract" \
  "$docs_index" \
  "$status_doc" \
  "$tasks_doc" \
  "$thesis_doc" \
  "$horizon_doc" \
  "$bets_doc" \
  "$avm_main" \
  "$avm_json_guard" \
  "$semantic_diff_runner" \
  "$semantic_diff_guard" \
  "$gas_calibration_set_guard" \
  "$native_instruction_surface_guard" \
  "$native_gas_modes_guard" \
  "$gas_surface_registry" \
  "$gas_surface_registry_guard" \
  "$native_policy_runner" \
  "$native_policy_runner_guard" \
  "$native_consts" \
  "$native_prelude" \
  Makefile
do
  require_file "$f"
done

require_literal "$contract" "# Effect Ledger Contract"
require_literal "$contract" "schema and tooling"
require_literal "$contract" "## Effect Ledger v0"
require_literal "$contract" "\"schema\": \"oren.effect-ledger.v0\""
require_literal "$contract" "\"determinism_grade\": \"replayable-host\""
require_literal "$contract" "\"domain\": \"FS\""
require_literal "$contract" "\"operation\": \"read_file\""
require_literal "$contract" "\"decision\": \"allow\""
require_literal "$contract" "\"denial_reason\": null"
require_literal "$contract" "\"budget_delta\""
require_literal "$contract" "\"input_digest\""
require_literal "$contract" "\"output_digest\""
require_literal "$contract" "\"redaction\""
require_literal "$contract" "\"replay_mode\""
require_literal "$contract" "\"schedule_epoch\""
require_literal "$contract" "\"source_span\""
require_literal "$contract" "Denial is data"
require_literal "$contract" "backend-comparable"
require_literal "$contract" "make verify-effect-ledger-contract"
require_literal "$contract" "make verify-avm-effect-ledger-json"
require_literal "$contract" "effect_ledger_summary"
require_literal "$contract" "oren.effect-ledger-summary.v0"
require_literal "$contract" "\"determinism\""
require_literal "$contract" "\"wall_ms\""
require_literal "$contract" "oren.semantic-diff.v0"
require_literal "$contract" "oren.native-package-policy-run.v0"
require_literal "$contract" "oren.native-capsule-effect-gates.v0"
require_literal "$contract" "oren.native-capsule-resource-checks.v0"
require_literal "$contract" "oren.gas-surface.v0"
require_literal "$contract" "oren.gas-surface-calibration.v0"
require_literal "$contract" "oren.gas-surface-calibration-set.v0"
require_literal "$contract" "oren.native-instruction-surface-decision.v0"
require_literal "$contract" "oren.avm-canonical-sidecar-gas.v0"
require_literal "$contract" "avm_opcode_cost_v0"
require_literal "$contract" "native_stmt_loop_tick_v0"
require_literal "$contract" "native_basic_block_tick_v0"
require_literal "$contract" "native_block_weighted_tick_v0"
require_literal "$contract" "native/OBC gas surfaces"
require_literal "$contract" "non-comparable"
require_literal "$contract" "not_a_conversion"
require_literal "$contract" "basic-block"
require_literal "$contract" "block-weighted"

require_literal "$cap_contract" "docs/EFFECT_LEDGER_CONTRACT.md"
require_literal "$cap_contract" "make verify-effect-ledger-contract"
require_literal "$docs_index" "docs/EFFECT_LEDGER_CONTRACT.md"
require_literal "$docs_index" "docs/GAS_SURFACE_REGISTRY.md"
require_literal "$tasks_doc" "docs/EFFECT_LEDGER_CONTRACT.md"
require_literal "$status_doc" "Effect ledger contract"
require_literal "$status_doc" "make verify-backend-semantic-diff"
require_literal "$status_doc" "make verify-gas-surface-registry"
require_literal "$thesis_doc" "effect ledgers"
require_literal "$horizon_doc" "Effect-ledger"
require_literal "$bets_doc" "effect-ledger schema"
require_literal "$bets_doc" "scripts/run_backend_semantic_diff.sh"
require_literal Makefile "verify-effect-ledger-contract:"
require_literal Makefile "verify-avm-effect-ledger-json:"
require_literal Makefile "verify-backend-semantic-diff:"
require_literal Makefile "verify-backend-semantic-diff-gas-calibration:"
require_literal Makefile "verify-backend-semantic-diff-gas-branch-calibration:"
require_literal Makefile "verify-backend-gas-surface-calibration-set:"
require_literal Makefile "verify-backend-native-instruction-surface-decision:"
require_literal Makefile "verify-native-gas-accounting-modes:"
require_literal Makefile "verify-gas-surface-registry:"
require_literal Makefile "tests/fixtures/backend_semantic_diff_gas_calibration.oren"
require_literal Makefile "tests/fixtures/backend_semantic_diff_gas_branch_calibration.oren"
require_literal Makefile "tests/fixtures/backend_semantic_diff_gas_alloc_calibration.oren"
require_literal Makefile "scripts/verify_effect_ledger_contract.sh"
require_literal Makefile "scripts/verify_avm_effect_ledger_json.sh"
require_literal Makefile "verify-effect-ledger-contract: verify-avm-effect-ledger-json"
require_literal Makefile "./scripts/verify_backend_semantic_diff.sh"
require_literal Makefile "test: verify-capability-runtime-contract verify-capability-metadata verify-capability-manifest-policy verify-effect-ledger-contract verify-avm-package-policy-runner verify-native-package-policy-runner verify-native-capsule-resource-checks verify-native-gas-accounting-modes verify-gas-surface-registry verify-public-readme-positioning verify-avm-spawn-channel-args test-native-quick"
require_literal "$avm_main" "print_effect_ledger_summary_json"
require_literal "$avm_main" "effect_ledger_summary"
require_literal "$avm_main" "oren.effect-ledger-summary.v0"
require_literal "$avm_main" "avm_error_fields"
require_literal "$avm_main" "\\\"status\\\""
require_literal "$avm_main" "\\\"error\\\""
require_literal "$avm_main" "oren.gas-surface.v0"
require_literal "$avm_main" "avm_opcode_cost_v0"
require_literal "$avm_main" "avm_canonical"
require_literal "$avm_main" "runtime_path_aware"
require_literal "$avm_main" "cross_arch_comparable"
require_literal "$avm_main" "conversion_ready"
require_literal "$avm_main" "runtime_profile"
require_literal "$avm_main" "\\\"wall_ms\\\""
require_literal "scripts/verify_avm_effect_ledger_json.sh" "effect_ledger_summary"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "AVM_GAS=1"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "budget exceeded (gas)"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "status=error"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "AVM_LOG_BYTES=4"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "AVM_TIMEOUT_MS=1000"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "wall_ms"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "oren.gas-surface.v0"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "avm_opcode_cost_v0"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "AVM canonical gas surface"
require_literal "scripts/verify_avm_effect_ledger_json.sh" "conversion-ready AVM canonical gas surface"
require_literal "$semantic_diff_runner" "oren.semantic-diff.v0"
require_literal "$semantic_diff_runner" "stdout_sha256"
require_literal "$semantic_diff_runner" "expected_line_present_all"
require_literal "$semantic_diff_runner" "effect_ledger_summary"
require_literal "$semantic_diff_runner" "budget_deltas"
require_literal "$semantic_diff_runner" "gas_surfaces"
require_literal "$semantic_diff_runner" "gas_surface_comparable_native_obc"
require_literal "$semantic_diff_runner" "gas_surface_calibration"
require_literal "$semantic_diff_runner" "oren.gas-surface-calibration.v0"
require_literal "$semantic_diff_runner" "oren.avm-canonical-sidecar-gas.v0"
require_literal "$semantic_diff_runner" "semantic_diff_same_source_fixture"
require_literal "$semantic_diff_runner" "same-source AVM canonical sidecar evidence"
require_literal "$semantic_diff_runner" "certification_status"
require_literal "$semantic_diff_runner" "certification_failure_reasons"
require_literal "$semantic_diff_runner" "certification_warnings"
require_literal "$semantic_diff_runner" "test_injection"
require_literal "$semantic_diff_runner" "same_run_stderr_equal"
require_literal "$semantic_diff_runner" "same_run_exit_code_equal"
require_literal "$semantic_diff_runner" "native_exit_code"
require_literal "$semantic_diff_runner" "sidecar_exit_code"
require_literal "$semantic_diff_runner" "budget_exceeded_source"
require_literal "$semantic_diff_runner" "sidecar_error"
require_literal "$semantic_diff_runner" "native_stdout_sha256"
require_literal "$semantic_diff_runner" "sidecar_stdout_sha256"
require_literal "$semantic_diff_runner" "obc_surface_unit_scope"
require_literal "$semantic_diff_runner" "obc_surface_avm_canonical"
require_literal "$semantic_diff_runner" "not_a_conversion"
require_literal "$semantic_diff_runner" "native and OBC gas surfaces differ"
require_literal "$semantic_diff_runner" "OREN_NATIVE_RUN_JSON=1"
require_literal "$semantic_diff_runner" "OREN_NATIVE_GAS_ACCOUNTING=dynamic-emitter"
require_literal "$semantic_diff_runner" "native runtime path-aware emitter gas surface"
require_literal "$semantic_diff_runner" "oren.native-run.v0"
require_literal "$semantic_diff_runner" "native_effect_ledger_summary_schema_ok"
require_literal "$semantic_diff_runner" "domain_gates"
require_literal "$semantic_diff_runner" "native_domain_gates_schema_ok"
require_literal "$semantic_diff_runner" "resource_checks"
require_literal "$semantic_diff_runner" "native_resource_checks_schema_ok"
require_literal "$semantic_diff_runner" "obc_run_json_schema_ok"
require_literal "$semantic_diff_runner" "obc_run_json_status_ok"
require_literal "$semantic_diff_runner" "obc_run_json_error_null"
require_literal "$semantic_diff_runner" "obc_effect_ledger_summary_schema_ok"
require_literal "$semantic_diff_runner" "ledger_available_backends"
require_literal "$semantic_diff_runner" "ledger_missing_backends"
require_literal "$semantic_diff_runner" "build/reports/"
require_literal "$semantic_diff_guard" "oren.semantic-diff.v0"
require_literal "$semantic_diff_guard" "native_run_json_schema_ok"
require_literal "$semantic_diff_guard" "native_effect_ledger_summary_schema_ok"
require_literal "$semantic_diff_guard" "native_domain_gates_schema_ok"
require_literal "$semantic_diff_guard" "obc_run_json_schema_ok"
require_literal "$semantic_diff_guard" "obc_run_json_status_ok"
require_literal "$semantic_diff_guard" "obc_run_json_error_null"
require_literal "$semantic_diff_guard" "obc_effect_ledger_summary_schema_ok"
require_literal "$semantic_diff_guard" "budget_deltas_comparable_all_backends"
require_literal "$semantic_diff_guard" "backend run JSON ledger export is not implemented"
require_literal "$semantic_diff_guard" "domain_gates"
require_literal "$semantic_diff_guard" "oren.native-capsule-effect-gates.v0"
require_literal "$semantic_diff_guard" "resource_checks"
require_literal "$semantic_diff_guard" "oren.native-capsule-resource-checks.v0"
require_literal "$semantic_diff_guard" "tracked_live_scan"
require_literal "$semantic_diff_guard" "native_dynamic_emitter_tick_v0"
require_literal "$semantic_diff_guard" "backend-local runtime-path-aware evidence"
require_literal "$semantic_diff_guard" "gas_surface_conversion_ready"
require_literal "$semantic_diff_guard" "native_surface_conversion_ready"
require_literal "$semantic_diff_guard" "native_surface_unit_scope"
require_literal "$semantic_diff_guard" "native_surface_target_arch"
require_literal "$semantic_diff_guard" "native_surface_unit_family"
require_literal "$semantic_diff_guard" "fixed_width_instruction_span"
require_literal "$semantic_diff_guard" "emitted_byte_span"
require_literal "$semantic_diff_guard" "oren.gas-surface.v0"
require_literal "$semantic_diff_guard" "avm_opcode_cost_v0"
require_literal "$semantic_diff_guard" "avm_canonical"
require_literal "$semantic_diff_guard" "conversion-ready AVM canonical target"
require_literal "$semantic_diff_guard" "gas_surfaces"
require_literal "$semantic_diff_guard" "gas_surface_comparable_native_obc"
require_literal "$semantic_diff_guard" "gas_surface_calibration"
require_literal "$semantic_diff_guard" "oren.gas-surface-calibration.v0"
require_literal "$semantic_diff_guard" "oren.avm-canonical-sidecar-gas.v0"
require_literal "$semantic_diff_guard" "AVM canonical sidecar"
require_literal "$semantic_diff_guard" "not package-policy binding yet"
require_literal "$semantic_diff_guard" "not_a_conversion"
require_literal "$semantic_diff_guard" "native and OBC gas surfaces differ"
require_literal "$gas_calibration_set_guard" "oren.gas-surface-calibration-set.v0"
require_literal "$gas_calibration_set_guard" "oren.gas-surface-conversion-decision.v0"
require_literal "$gas_calibration_set_guard" "OREN_GAS_SURFACE_CALIBRATION_MIN_SPREAD"
require_literal "$gas_calibration_set_guard" "OREN_GAS_SURFACE_CALIBRATION_SEMANTIC_RUN_TIMEOUT_SECS"
require_literal "$gas_calibration_set_guard" "single_ratio_unsafe"
require_literal "$gas_calibration_set_guard" "required_next_surface"
require_literal "$gas_calibration_set_guard" "native_instruction_equivalent_or_package_bound_avm_canonical_sidecar_gas"
require_literal "$gas_calibration_set_guard" "surface_metadata_blocks_conversion"
require_literal "$gas_calibration_set_guard" "avm_canonical_sidecar_available"
require_literal "$gas_calibration_set_guard" "avm_canonical_sidecar_stderr_equal"
require_literal "$gas_calibration_set_guard" "avm_canonical_sidecar_exit_code_equal"
require_literal "$gas_calibration_set_guard" "avm_canonical_sidecar_exit_code_equal_all"
require_literal "$gas_calibration_set_guard" "avm_canonical_sidecar_warning_free"
require_literal "$gas_calibration_set_guard" "avm_canonical_sidecar_test_injection_free"
require_literal "$gas_calibration_set_guard" "package_policy_may_use_avm_sidecar"
require_literal "$gas_calibration_set_guard" "native_surface_conversion_ready"
require_literal "$gas_calibration_set_guard" "native_surface_unit_scope"
require_literal "$gas_calibration_set_guard" "native_surface_target_arch"
require_literal "$gas_calibration_set_guard" "native_surface_unit_family"
require_literal "$gas_calibration_set_guard" "obc_surface_unit_scope"
require_literal "$gas_calibration_set_guard" "obc_surface_conversion_ready"
require_literal "$gas_calibration_set_guard" "obc_surface_avm_canonical"
require_literal "$gas_calibration_set_guard" "backend_semantic_diff_gas_calibration.oren"
require_literal "$gas_calibration_set_guard" "backend_semantic_diff_gas_branch_calibration.oren"
require_literal "$gas_calibration_set_guard" "backend_semantic_diff_gas_call_calibration.oren"
require_literal "$gas_calibration_set_guard" "backend_semantic_diff_gas_alloc_calibration.oren"
require_literal "$gas_calibration_set_guard" "required_sample_classes"
require_literal "$gas_calibration_set_guard" "call_heavy"
require_literal "$gas_calibration_set_guard" "alloc_heavy"
require_literal "$gas_calibration_set_guard" "verify_backend_semantic_diff.sh"
require_literal "$native_instruction_surface_guard" "oren.native-instruction-surface-decision.v0"
require_literal "$native_instruction_surface_guard" "OREN_NATIVE_INSTRUCTION_SURFACE_SEMANTIC_RUN_TIMEOUT_SECS"
require_literal "$native_instruction_surface_guard" "whole_binary_disasm_not_runtime_path"
require_literal "$native_instruction_surface_guard" "native_dynamic_emitter_tick_v0"
require_literal "$native_instruction_surface_guard" "observed_runtime_surface_target_arch"
require_literal "$native_instruction_surface_guard" "observed_runtime_surface_unit_family"
require_literal "$native_instruction_surface_guard" "observed_obc_surface_unit_scope"
require_literal "$native_instruction_surface_guard" "observed_obc_surface_avm_canonical"
require_literal "$native_instruction_surface_guard" "native_instruction_equivalent_or_package_bound_avm_canonical_sidecar_gas"
require_literal "$native_instruction_surface_guard" "avm_canonical_sidecar_available"
require_literal "$native_instruction_surface_guard" "avm_canonical_sidecar_stderr_equal"
require_literal "$native_instruction_surface_guard" "avm_canonical_sidecar_exit_code_equal"
require_literal "$native_instruction_surface_guard" "avm_canonical_sidecar_exit_code_equal_all"
require_literal "$native_instruction_surface_guard" "avm_canonical_sidecar_warning_free"
require_literal "$native_instruction_surface_guard" "avm_canonical_sidecar_test_injection_free"
require_literal "$native_instruction_surface_guard" "package_policy_may_use_avm_sidecar"
require_literal "$native_instruction_surface_guard" "native_whole_binary_disasm_instruction_count_v0"
require_literal "$native_instruction_surface_guard" "backend_semantic_diff_gas_call_calibration.oren"
require_literal "$native_instruction_surface_guard" "backend_semantic_diff_gas_alloc_calibration.oren"
require_literal "$native_instruction_surface_guard" "required_sample_classes"
require_literal "$native_instruction_surface_guard" "alloc_heavy"
require_literal "$native_gas_modes_guard" "native_gas_accounting_modes.oren"
require_literal "$native_gas_modes_guard" "native_loop_safepoint_tick_v0"
require_literal "$native_gas_modes_guard" "native_stmt_loop_tick_v0"
require_literal "$native_gas_modes_guard" "native_basic_block_tick_v0"
require_literal "$native_gas_modes_guard" "native_block_weighted_tick_v0"
require_literal "$native_gas_modes_guard" "native_dynamic_emitter_tick_v0"
require_literal "$native_gas_modes_guard" "unit_scope"
require_literal "$native_gas_modes_guard" "conversion_ready"
require_literal "$native_gas_modes_guard" "avm_canonical"
require_literal "$native_gas_modes_guard" "unit_family"
require_literal "$native_gas_modes_guard" "target_arch"
require_literal "$native_gas_modes_guard" "--no-cache"
require_literal "$native_gas_modes_guard" "basic-block must stay distinct from statement gas"
require_literal "$native_gas_modes_guard" "block-weighted must stay distinct from basic-block and statement gas"
require_literal "$native_gas_modes_guard" "instruction_equivalent_reserved"
require_literal "$native_gas_modes_guard" "instruction-equivalent gas must stay reserved"
require_literal "lib/compiler/compiler/012_build_cache.oren" "native_gas_accounting="
require_literal "lib/compiler/compiler/040_build_pipeline/010_main.oren" "cfg[\"native_gas_accounting\"] = \"basic-block\""
require_literal "lib/compiler/compiler/040_build_pipeline/010_main.oren" "cfg[\"native_gas_accounting\"] = \"block-weighted\""
require_literal "lib/compiler/compiler/040_build_pipeline/010_main.oren" "cfg[\"native_gas_accounting\"] = \"dynamic-emitter\""
require_literal "lib/runtime_native/000_prelude_sys.oren" "oren.native-run.v0"
require_literal "lib/runtime_native/000_prelude_sys.oren" "OREN_NATIVE_RUN_JSON"
require_literal "lib/runtime_native/000_prelude_sys.oren" "native_runtime_heap_used_bytes"
require_literal "lib/runtime_native/000_prelude_sys.oren" "native_runtime_gas_surface_json"
require_literal "lib/runtime_native/000_prelude_sys.oren" "native_runtime_backend_local_gas_surface_json"
require_literal "lib/runtime_native/000_prelude_sys.oren" "oren.gas-surface.v0"
require_literal "lib/runtime_native/000_prelude_sys.oren" "backend_local"
require_literal "lib/runtime_native/000_prelude_sys.oren" "native_statement_or_op"
require_literal "lib/runtime_native/000_prelude_sys.oren" "conversion_ready"
require_literal "lib/runtime_native/000_prelude_sys.oren" "fixed_width_instruction_span"
require_literal "lib/runtime_native/000_prelude_sys.oren" "emitted_byte_span"
require_literal "lib/runtime_native/000_prelude_sys.oren" "basic-block"
require_literal "lib/runtime_native/000_prelude_sys.oren" "block-weighted"
require_literal "lib/runtime_native/000_prelude_sys.oren" "dynamic-emitter"
require_literal "$gas_surface_registry" "avm_opcode_cost_v0"
require_literal "$gas_surface_registry" "native_loop_safepoint_tick_v0"
require_literal "$gas_surface_registry" "native_stmt_loop_tick_v0"
require_literal "$gas_surface_registry" "native_basic_block_tick_v0"
require_literal "$gas_surface_registry" "native_block_weighted_tick_v0"
require_literal "$gas_surface_registry" "native_dynamic_emitter_tick_v0"
require_literal "$gas_surface_registry" "make verify-gas-surface-registry"
require_literal "$gas_surface_registry_guard" "oren.gas-surface-registry-check.v0"
require_literal "$gas_surface_registry_guard" "verify-backend-semantic-diff-gas-alloc-calibration:"
require_literal "$native_policy_runner" "oren.native-package-policy-run.v0"
require_literal "$native_policy_runner" "effect_ledger"
require_literal "$native_policy_runner" "runner_wall_only"
require_literal "$native_policy_runner" "runner_wall_native_heap"
require_literal "$native_policy_runner" "runner_wall_child_cpu"
require_literal "$native_policy_runner" "runner_wall_native_gas"
require_literal "$native_policy_runner" "runner_wall_avm_canonical_gas"
require_literal "$native_policy_runner" "native-run-json-live-scan"
require_literal "$native_policy_runner" "runner-child-rusage"
require_literal "$native_policy_runner" "native-run-json-stmt-loop-tick"
require_literal "$native_policy_runner" "OREN_NATIVE_PACKAGE_POLICY_AVM_SIDECAR"
require_literal "$native_policy_runner" "OREN_NATIVE_PACKAGE_POLICY_GAS_PROFILE"
require_literal "$native_policy_runner" "native_package_policy_same_source_artifact"
require_literal "$native_policy_runner" "package-bound AVM canonical sidecar gas"
require_literal "$native_policy_runner" "avm-canonical-sidecar"
require_literal "$native_policy_runner" "enforcement_profile"
require_literal "$native_policy_runner" "requested_enforcement_profile"
require_literal "$native_policy_runner" "certification_status"
require_literal "$native_policy_runner" "certification_failure_reasons"
require_literal "$native_policy_runner" "certification_warnings"
require_literal "$native_policy_runner" "test_injection"
require_literal "$native_policy_runner" "same_run_stderr_equal"
require_literal "$native_policy_runner" "same_run_exit_code_equal"
require_literal "$native_policy_runner" "native_exit_code"
require_literal "$native_policy_runner" "sidecar_exit_code"
require_literal "$native_policy_runner" "package_policy_may_use_reason"
require_literal "$native_policy_runner" "budget_exceeded_source"
require_literal "$native_policy_runner" "sidecar_error"
require_literal "$native_policy_runner" "OREN_NATIVE_GAS_ACCOUNTING"
require_literal "$native_policy_runner" "budget_heap_bytes"
require_literal "$native_policy_runner" "budget_gas"
require_literal "$native_policy_runner" "budget_cpu_ms"
require_literal "$native_policy_runner" "native_stmt_loop_tick_v0"
require_literal "$native_policy_runner" "gas_surface_id"
require_literal "$native_policy_runner_guard" "oren.native-capsule-effect-gates.v0"
require_literal "$native_policy_runner_guard" "native capsule effect gates"
require_literal "$native_policy_runner_guard" "oren.gas-surface.v0"
require_literal "$native_policy_runner_guard" "native_package_policy_runner_heap_ok.oren"
require_literal "$native_policy_runner_guard" "native_package_policy_runner_heap_fail.oren"
require_literal "$native_policy_runner_guard" "native_package_policy_runner_gas_ok.oren"
require_literal "$native_policy_runner_guard" "native_package_policy_runner_gas_fail.oren"
require_literal "$native_policy_runner_guard" "OREN_NATIVE_PACKAGE_POLICY_AVM_SIDECAR"
require_literal "$native_policy_runner_guard" "OREN_NATIVE_PACKAGE_POLICY_GAS_PROFILE"
require_literal "$native_policy_runner_guard" "OREN_NATIVE_PACKAGE_POLICY_GAS_PROFILE=native-stmt"
require_literal "$native_policy_runner_guard" "--gas-profile avm-sidecar"
require_literal "$native_policy_runner_guard" "--gas-profile auto"
require_literal "$native_policy_runner_guard" "dispatcher default"
require_literal "$native_policy_runner_guard" "--gas-profile applies only to --backend native"
require_literal "$native_policy_runner_guard" "native_package_policy_same_source_artifact"
require_literal "$native_policy_runner_guard" "avm_opcode_cost_v0"
require_literal "$native_policy_runner_guard" "runner_wall_avm_canonical_gas"
require_literal "$native_policy_runner_guard" "avm-canonical-sidecar"
require_literal "$native_policy_runner_guard" "enforcement_profile"
require_literal "$native_policy_runner_guard" "certification_status"
require_literal "$native_policy_runner_guard" "certification_failure_reasons"
require_literal "$native_policy_runner_guard" "certification_warnings"
require_literal "$native_policy_runner_guard" "OREN_NATIVE_PACKAGE_POLICY_TEST_AVM_SIDECAR_STDOUT_SUFFIX"
require_literal "$native_policy_runner_guard" "OREN_NATIVE_PACKAGE_POLICY_TEST_AVM_SIDECAR_STDERR_SUFFIX"
require_literal "$native_policy_runner_guard" "OREN_NATIVE_PACKAGE_POLICY_TEST_AVM_SIDECAR_EXIT_CODE"
require_literal "$native_policy_runner_guard" "test_injection"
require_literal "$native_policy_runner_guard" "stdout_suffix"
require_literal "$native_policy_runner_guard" "stderr_suffix"
require_literal "$native_policy_runner_guard" "exit_code"
require_literal "$native_policy_runner_guard" "stdout_mismatch"
require_literal "$native_policy_runner_guard" "stderr_mismatch"
require_literal "$native_policy_runner_guard" "exit_code_mismatch"
require_literal "$native_policy_runner_guard" "sidecar_exit_nonzero"
require_literal "$native_policy_runner_guard" "package AVM canonical sidecar gas could not be certified for native run"
require_literal "$native_policy_runner_guard" "same_run_stderr_equal"
require_literal "$native_policy_runner_guard" "same_run_exit_code_equal"
require_literal "$native_policy_runner_guard" "native_exit_code"
require_literal "$native_policy_runner_guard" "sidecar_exit_code"
require_literal "$native_policy_runner_guard" "package_policy_may_use_reason"
require_literal "$native_policy_runner_guard" "budget_exceeded_source"
require_literal "$native_policy_runner_guard" "sidecar_error"
require_literal "$native_policy_runner_guard" "must be native-stmt, avm-sidecar, or auto"
require_literal "$native_policy_runner_guard" "native_package_policy_runner_gas_stmt_fail.oren"
require_literal "$native_policy_runner_guard" "native_package_policy_runner_cpu_ok.oren"
require_literal "$native_policy_runner_guard" "native_package_policy_runner_cpu_fail.oren"
require_literal "$native_policy_runner_guard" "package native heap budget exceeded"
require_literal "$native_policy_runner_guard" "package native gas budget exceeded"
require_literal "$native_policy_runner_guard" "package AVM canonical sidecar gas budget exceeded"
require_literal "$native_policy_runner_guard" "package native CPU budget exceeded"
require_literal "$native_consts" "native_capsule_effect_gate_summary_json"
require_literal "$native_consts" "native_capsule_effect_gate_note"
require_literal "$native_consts" "native_capsule_resource_check_summary_json"
require_literal "$native_consts" "native_capsule_resource_check_note"
require_literal "$native_consts" "native_runtime_heap_used_bytes"
require_literal "$native_consts" "native_runtime_gas_safepoint_ticks"
require_literal "$native_prelude" "domain_gates"
require_literal "$native_prelude" "resource_checks"

echo "effect ledger contract verify OK"
