#!/usr/bin/env bash
set -euo pipefail

# Generate `avm_root_pubkey.inc` for AVM builds.
#
# Inputs (optional, in priority order):
#  1) AVM_EMBED_ROOT_PUBKEY_HEX: comma-separated list of 64-hex ed25519 pubkeys (32 bytes each)
#  2) ../oren-ca/avm_root_pubkeys.hex: one 64-hex pubkey per line (blank lines + #comments allowed)
#
# If no keys are provided, emits COUNT=0 and all-zero slots (safe dev default).
#
# This file only contains public keys (no secrets).

max_slots=4

read_keys_from_env() {
  local s="${AVM_EMBED_ROOT_PUBKEY_HEX:-}"
  if [[ -z "${s}" ]]; then
    return 1
  fi
  # split on commas
  IFS=',' read -r -a parts <<< "${s}"
  for p in "${parts[@]}"; do
    # trim spaces
    local t="${p//[[:space:]]/}"
    [[ -z "${t}" ]] && continue
    echo "${t}"
  done
  return 0
}

read_keys_from_file() {
  local f="../oren-ca/avm_root_pubkeys.hex"
  if [[ ! -f "${f}" ]]; then
    return 1
  fi
  # allow comments and whitespace
  while IFS= read -r line; do
    # strip leading/trailing whitespace
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "${line}" ]] && continue
    [[ "${line}" == \#* ]] && continue
    # allow either 64-hex or 0x-prefixed 64-hex
    if [[ "${line}" == 0x* || "${line}" == 0X* ]]; then
      line="${line:2}"
    fi
    line="${line//[[:space:]]/}"
    echo "${line}"
  done < "${f}"
  return 0
}

collect_keys() {
  if read_keys_from_env; then
    return 0
  fi
  if read_keys_from_file; then
    return 0
  fi
  return 1
}

hex_to_c_bytes_32() {
  local hex="$1"
  if [[ ! "${hex}" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "ERROR: expected 64 hex chars for pubkey, got: ${hex}" >&2
    exit 2
  fi
  local i=0
  local out=""
  while [[ $i -lt 64 ]]; do
    local byte_hex="${hex:$i:2}"
    # shellcheck disable=SC2059
    local byte_dec=$((16#${byte_hex}))
    out+="${byte_dec},"
    i=$((i+2))
  done
  # format as 2 lines of 16 bytes each
  local a=(${out//,/ })
  printf "    "
  for j in $(seq 0 15); do
    printf "%s" "${a[$j]}"
    [[ $j -ne 15 ]] && printf ","
  done
  printf "\n    "
  for j in $(seq 16 31); do
    printf "%s" "${a[$j]}"
    [[ $j -ne 31 ]] && printf ","
  done
  printf "\n"
}

emit_zero_slot() {
  cat <<'EOF'
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
EOF
}

keys=()
if collected="$(collect_keys)"; then
  while IFS= read -r k; do
    [[ -z "${k}" ]] && continue
    keys+=("${k}")
    [[ ${#keys[@]} -ge ${max_slots} ]] && break
  done <<< "${collected}"
fi

count="${#keys[@]}"

cat <<EOF
// Generated file: build-time AVM root trust anchors (public keys only).
//
// This file is safe to distribute and safe to embed: it contains public keys, not secrets.
// Do NOT commit private keys to the repo (use ../oren-ca/ for secrets).
//
// Generated by: tools/gen_avm_root_pubkeys_inc.sh
// Source priority:
//   1) AVM_EMBED_ROOT_PUBKEY_HEX (comma-separated 64-hex)
//   2) ../oren-ca/avm_root_pubkeys.hex (one 64-hex per line)
//
// Slot count:
//   AVM_TRUSTED_ROOT_PUBKEYS_COUNT controls which slots are active.

#define AVM_TRUSTED_ROOT_PUBKEYS_SLOTS ${max_slots}
EOF

for i in $(seq 0 $((max_slots-1))); do
  echo ""
  echo "static const unsigned char AVM_TRUSTED_ROOT_PUBKEY${i}_BYTES[32] = {"
  if [[ $i -lt $count ]]; then
    hex_to_c_bytes_32 "${keys[$i]}"
  else
    emit_zero_slot
  fi
  echo "};"
done

cat <<EOF

static const unsigned char* const AVM_TRUSTED_ROOT_PUBKEYS[AVM_TRUSTED_ROOT_PUBKEYS_SLOTS] = {
    AVM_TRUSTED_ROOT_PUBKEY0_BYTES,
    AVM_TRUSTED_ROOT_PUBKEY1_BYTES,
    AVM_TRUSTED_ROOT_PUBKEY2_BYTES,
    AVM_TRUSTED_ROOT_PUBKEY3_BYTES,
};

static const size_t AVM_TRUSTED_ROOT_PUBKEYS_COUNT = ${count};
EOF

